"""Customer-segment value, revenue concentration (Pareto), and RFM segmentation."""

from __future__ import annotations

import pandas as pd


def segment_summary(df: pd.DataFrame) -> pd.DataFrame:
    """Compare Customer Type (Consumer/Corporate/Small Business/Home Office) on
    value, not just raw sales: revenue/customer, orders/customer, basket size,
    margin, and average discount rate."""
    g = df.groupby("Customer Type")
    out = g.agg(
        revenue=("revenue", "sum"),
        gross_profit=("gross_profit", "sum"),
        customers=("Customer Name", "nunique"),
        units=("order_qty", "sum"),
        avg_discount_pct=("discount_pct", "mean"),
    )
    out["orders"] = g["base_order_id"].nunique()
    out["margin_pct"] = out["gross_profit"] / out["revenue"]
    out["revenue_per_customer"] = out["revenue"] / out["customers"]
    out["orders_per_customer"] = out["orders"] / out["customers"]
    out["units_per_order"] = out["units"] / out["orders"]
    return out.sort_values("revenue", ascending=False)


def pareto_concentration(df: pd.DataFrame) -> dict:
    """Share of total revenue generated by the top 10% / 20% of customers by
    lifetime revenue."""
    cust_rev = df.groupby("Customer Name")["revenue"].sum().sort_values(ascending=False)
    total = cust_rev.sum()
    n = len(cust_rev)
    top10_n = max(1, int(round(n * 0.10)))
    top20_n = max(1, int(round(n * 0.20)))
    return {
        "n_customers": n,
        "top10_customer_count": top10_n,
        "top10_revenue_share": cust_rev.iloc[:top10_n].sum() / total,
        "top20_customer_count": top20_n,
        "top20_revenue_share": cust_rev.iloc[:top20_n].sum() / total,
        "customer_revenue": cust_rev,
    }


def lorenz_curve(df: pd.DataFrame) -> pd.DataFrame:
    """Cumulative share of customers vs. cumulative share of revenue, for
    plotting the concentration curve against the line of equality."""
    cust_rev = df.groupby("Customer Name")["revenue"].sum().sort_values(ascending=False)
    n = len(cust_rev)
    cum_customers = pd.Series(range(1, n + 1)) / n
    cum_revenue = cust_rev.cumsum().values / cust_rev.sum()
    return pd.DataFrame({"cum_customer_share": cum_customers, "cum_revenue_share": cum_revenue})


def rfm_table(df: pd.DataFrame) -> pd.DataFrame:
    """Recency (days since last order, relative to the dataset's max date),
    Frequency (distinct orders), Monetary (lifetime revenue) per customer,
    scored 1-4 by quartile (4 = best) and segmented into named buckets."""
    snapshot = df["order_date"].max() + pd.Timedelta(days=1)

    g = df.groupby("Customer Name")
    rfm = g.agg(
        recency_days=("order_date", lambda s: (snapshot - s.max()).days),
        frequency=("base_order_id", "nunique"),
        monetary=("revenue", "sum"),
    )

    # Recency: lower is better -> reverse the quartile labels.
    rfm["R"] = pd.qcut(rfm["recency_days"], 4, labels=[4, 3, 2, 1]).astype(int)
    rfm["F"] = pd.qcut(rfm["frequency"].rank(method="first"), 4, labels=[1, 2, 3, 4]).astype(int)
    rfm["M"] = pd.qcut(rfm["monetary"], 4, labels=[1, 2, 3, 4]).astype(int)
    rfm["rfm_score"] = rfm["R"] + rfm["F"] + rfm["M"]

    def segment(row):
        if row["R"] >= 3 and row["F"] >= 3 and row["M"] >= 3:
            return "Champions"
        if row["R"] >= 3 and row["F"] >= 2:
            return "Loyal"
        if row["R"] >= 3 and row["M"] >= 3:
            return "High-Value Occasional"
        if row["R"] <= 2 and row["F"] >= 3 and row["M"] >= 3:
            return "At Risk (was high-value)"
        if row["R"] <= 2 and row["F"] <= 2 and row["M"] <= 2:
            return "Dormant"
        return "Potential Loyalist"

    rfm["segment"] = rfm.apply(segment, axis=1)
    return rfm.sort_values("monetary", ascending=False)


def rfm_segment_summary(rfm: pd.DataFrame) -> pd.DataFrame:
    out = rfm.groupby("segment").agg(
        customers=("monetary", "count"),
        total_revenue=("monetary", "sum"),
        avg_recency_days=("recency_days", "mean"),
        avg_frequency=("frequency", "mean"),
        avg_monetary=("monetary", "mean"),
    )
    out["customer_share"] = out["customers"] / out["customers"].sum()
    out["revenue_share"] = out["total_revenue"] / out["total_revenue"].sum()
    return out.sort_values("total_revenue", ascending=False)
